import {StyleSheet} from 'react-native';
import { SearchBar } from 'react-native-screens';
const  styles = StyleSheet.create({
    container:{
        flex: 1,
        height:"100%",
        width:"100%",
        backgroundColor:"#edf8fc",
    },
    header:{
        height:80,
        width:"100%",
       flexDirection:"row",
        alignItems:"center",
        marginTop:30,   
    },
    logo:{
        height:50,
         marginLeft:50,
         marginLeft:20,    
    },
    headerText:{
      marginLeft:10,
        width:190,
    },
    name:{
        fontSize:20,
        fontWeight:"bold"
    },
    post:{
        fontSize:12,
        fontWeight:"lighter",
        color:"#8C8C8C",

    },
    bell:{
        backgroundColor:"white",
        width:40,
        height:40,
        marginLeft:30,
        alignItems:'center',
        justifyContent:'center',
        
    },
    searchBar:{
        flexDirection:"row",
        backgroundColor:"white",
        alignItems:"center",
        width:255,
        borderRadius:10,
        height:48,
        marginLeft:10,
        marginTop:1,

    },
    searchImg:{
        width:20,
        marginLeft:10,
    },
    searchText:{
        fontSize:12,
        fontWeight:'light',
        color:"#babfbe",
        marginLeft:10,
    },
    filter:{
        borderRadius:10,
        alignItems:"center",
        justifyContent:"center",
        marginLeft:180,
        width:48,
        height:48,
       backgroundColor: '#8A19D6',
    },
    sliderContainer:{
        height:156,
        width:335,
        backgroundColor: '#b66dff',
        marginTop:10,
       marginHorizontal:15,
       flexDirection:"row",
       borderRadius:10,
       },
       sliderLeft:{
            width:50,
            height:50,
            marginTop:20,
            marginLeft:20,   
       },
       sliderText:{
        width:60,
        marginBottom:5,
        marginLeft:10,
        color:"#ffffff",
        fontSize:12,
       fontWeight:"400",
    },
    sliderText2:{
        width:132,
        height:33,
        marginLeft:10,
        fontSize:26,
        fontWeight:"900",
        color:"#ffffff",   
    },
    button:{
        width:130,
        marginTop:15,
        height:42,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor: '#8A19D6',
        borderRadius:10,
        marginLeft:7,
    },
    buttonText:{
        color:"#ffffff",
        fontSize:16,
        fontWeight:'600',       
    },
       sliderRight:{
        width:120,
        height:120,
        alignItems:'center',
        justifyContent:'center',
        marginLeft:130,
        marginTop:35,
        borderRadius:70,
        backgroundColor:'#a755fa',
    },
       sliderImg:{
        width:150,
        height:150,
        marginBottom:40,
        marginRight:10,
    },
    slider:{
        marginTop:10,
        marginLeft:150,
    },
    statContainer:{
        backgroundColor:"white",
        width:335,
        borderRadius:10,
        height:144,
        marginLeft:10,
        marginTop:10,
    },
    statText:{
        fontSize:20,
        fontWeight:'600',
        width:327,
        height:26,
        marginLeft:10,

    },
    stat:{
        flexDirection:"row",
        width:320,
        height:101,
        marginTop:15,
    },
   
    product:{
        width:100,
        height:101,
        backgroundColor:'#a755fa',
        marginLeft:10,
        justifyContent:"center",
        alignItems:"center",
        borderRadius:10,  
    },
    material:{
        width:40,
        height:61,
    },
    vender:{
        width:100,
        height:101,
        backgroundColor:'#a755fa',
        marginLeft:10,
        justifyContent:"center",
        alignItems:"center",
        borderRadius:10,     
    },
    stock:{
        width:100,
        height:101,
        backgroundColor:'#a755fa',
        marginLeft:10,
        justifyContent:"center",
        alignItems:"center",
        borderRadius:10,    
    },
    postContainer:{
        width:335,
        height:205,
        backgroundColor:"#edf8fc",
        marginTop:20,
    },
    heading:{
        height:26,
        width:327,
        flexDirection:"row",
    },
    postIcon:{
        width:32,
        height:32,
        borderRadius:20,
        alignItems:"center",
        justifyContent:"center",
        backgroundColor: '#8A19D6',
        marginLeft:10,
    },
    postCol:{
        marginTop:10,
        width:335,
        height:78,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
        backgroundColor:'white',
    },
    imgBox:{
        width:48,
        height:48,
        backgroundColor: '#8A19D6',
        borderRadius:15,
        marginRight:10,
    }

   


});

export default styles;